/**
 * @file Automatically generated by barrelsby.
 */

import { DatabaseBootstrapper } from "./DatabaseBootstrapper";
import { ExternalProviderBootstrapper } from "./ExternalProvidersBootstrapper";
import { IBootstrapper } from "./IBootstrapper";

export const bootstrappers = [
    ExternalProviderBootstrapper,
    DatabaseBootstrapper
] as (new () => IBootstrapper)[];
