apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- "../../core"

commonLabels:
  app: production

namespace: production       

resources:
- namespace.yaml
- path-ingress.yaml
- host-ingress.yaml
- secret.yaml
- db-persistent-volume.yaml