apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.names.api.host_ingress }}
  labels:
    {{- toYaml .Values.labels.api.host_ingress | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: {{ .Values.namespace }}
spec:
  {{ if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.domain }}
      secretName: {{ .Values.ingress.tlsSecret }}
  {{ end }}
  ingressClassName: {{ .Values.ingress.name }}
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.names.api.service }}
            port:
              number: {{ .Values.ports.api }}
