# use node port, load balancing will be done by ingress
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    section: kurabu-api
    kind: service
spec:
  type: NodePort
  selector:
    section: kurabu-api
    kind: pod
  ports:
    - port: 15000
      targetPort: 15000
      