name: "Setup kubectl"
description: "Setup kubectl"
inputs:
  config_path:
    description: The location to store the config in
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup kubectl
      shell: bash
      run: |
        mkdir $(dirname ${{ inputs.config_path }})
        echo $KUBE_CONFIG | base64 --docode > ${{ inputs.config_path }}
        stat --printf="%s" ${{ inputs.config_path }}
