apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: prod
  labels:
    app: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kurabu-api
  template:
    metadata:
      labels:
        app: kurabu-api
    spec:
      containers:
      - name: kurabu-api
        image: rafaeltab/kurabu.api:2.0.11
        command:
          - "yarn run start --scope=@kurabu/api"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "250Mi"
            cpu: "100m"
        ports:
        - containerPort: 15000

      
         