apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: prod
  labels:
    app: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kurabu/api
  template:
    metadata:
      labels:
        app: kurabu/api
    spec:
      containers:
      - name: kurabu/api
        image: kurabu/api:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        ports:
        - containerPort: 15000

      
         