apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.kurabu.moe
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-api-service
            port:
              number: 15000
        
  - host: stage.kurabu.moe
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stage-api-service
            port:
              number: 15000
  - http:
      paths:
      - path: /prod
        pathType: Prefix
        backend:
          service:
            name: prod-api-service
            port:
              number: 15000
        
  - http:
      paths:
      - path: /stage
        pathType: Prefix
        backend:
          service:
            name: stage-api-service
            port:
              number: 15000
        
