apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.names.db.persistentVolume }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels.db.persistentVolume | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.db.size }}
  {{- toYaml .Values.storage.db.volumeSettings | nindent 2 }}
