apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.names.db.persistentVolumeClaim }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels.db.persistentVolumeClaim | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.labels.db.persistentVolume | nindent 6 }}
  {{- toYaml .Values.storage.db.volumeClaimSettings | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.storage.db.size }}
  