apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels.secret | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.api.keys.clientId }}: !!str {{ required "secrets.api.values.clientId is a required value" .Values.secrets.api.values.clientId }}
  {{ .Values.secrets.api.keys.clientSecret }}: !!str {{ required "secrets.api.values.clientSecret is a required value" .Values.secrets.api.values.clientSecret }}
  {{ .Values.secrets.api.keys.passwordEncryptionKey }}: !!str {{ required "secrets.api.values.passwordEncryptionKey is a required value" .Values.secrets.api.values.passwordEncryptionKey }}
  {{ .Values.secrets.api.keys.jwtEncryptionCertificate }}: !!str {{ required "secrets.api.values.jwtEncryptionCertificate is a required value" .Values.secrets.api.values.jwtEncryptionCertificate }}
  {{ .Values.secrets.api.keys.databaseUrl }}: !!str {{ required "secrets.api.values.databaseUrl is a required value" .Values.secrets.api.values.databaseUrl }}
  {{ .Values.secrets.api.keys.sendgridApiKey }}: !!str {{ required "secrets.api.values.sendgridApiKey is a required value" .Values.secrets.api.values.sendgridApiKey }}
  {{ .Values.secrets.api.keys.migrationPath }}: !!str {{ required "secrets.api.values.migrationPath is a required value" .Values.secrets.api.values.migrationPath }}
  {{ .Values.secrets.api.keys.emailDomain }}: !!str {{ required "secrets.api.values.emailDomain is a required value" .Values.secrets.api.values.emailDomain }}
  {{ .Values.secrets.api.keys.databaseSSL }}: !!str {{ required "secrets.api.values.databaseSSL is a required value" .Values.secrets.api.values.databaseSSL }}
  
  {{ .Values.secrets.db.keys.password }}: !!str {{ required "secrets.db.values.password is a required value" .Values.secrets.db.values.password }}
  {{ .Values.secrets.db.keys.user }}: !!str {{ required "secrets.db.values.user is a required value" .Values.secrets.db.values.user }}
  {{ .Values.secrets.db.keys.database }}: !!str {{ required "secrets.db.values.database is a required value" .Values.secrets.db.values.database }}
