# Use type node port sicne there will only ever be one instance
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    section: kurabu-db
    kind: service
spec:
  type: NodePort
  selector:
    section: kurabu-db
    kind: pod
  ports:
    - port: 5432
      targetPort: 5432
      