apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  namespace: stage
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:14.1
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "300Mi"
        cpu: "100m"
    ports:
    - containerPort: 5432
  volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName: db-persistent-volume-claim

      
         