apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-persistent-volume
  namespace: stage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/stage" 
  persistentVolumeReclaimPolicy: Retain
