config:
  kurabu:api.clientId:
    secure: AAABABCNnovRW975QoiUbVbMcSXmZ7xubk3krDjMYajCvJVgnNNV7HtP6V8KYEHCmyr43dC4gCl3QfaUguhiHw==
  kurabu:api.clientSecret:
    secure: AAABAEykp6ZQm5zrd3f/XixRrNzkATD7vjSGRvTDQ163ihSRL/DyX9Q5cgrBYc3jF8R8SaHDxhN4M28cyJrKixF7CRUiFgzoqJ6PMfu5VGvTQyEX9vKuzopSqTZATnnH
  kurabu:api.databaseSSL:
    secure: AAABAC4NI4c6dvASyQvL/8xsMjYkPwc0N+j1gwbhYe34qiXaVA==
  kurabu:api.databaseUrl:
    secure: AAABAM/jESKrgZg7lo480HWj9dLUHpt+1H6jkMMS0gZMJLqrAPKuBkLEIMeaXtSXFGLVgIXJcaK+diVYDuxDubJdFKv65tx0M4Qh/LfPdn5bPnLK0sxm7BwU9UZMZe2zuWtxvKeDf94=
  kurabu:api.emailDomain:
    secure: AAABAI6JEyD0NgB5lQcOrHzU33nVVeJPvTCIAh3LkCpFNNvWDIPWBnKc
  kurabu:api.jwtEncryptionCertificate:
    secure: AAABAInEK9XSlLlxMpTSFpsSv+PzrRYID/UpmEtAXtyQeHo8UsvQ02FRFHvkJgd2tImu0GCCdRc8yD7McDi3GSIGNRbtOthuOsP3rqRca4VaS0YN4Wse0FPY0b7KDnhA2StYVRPUQRNzr/AbK0laadmCo6KK1RCm+pJ0s8EZiC1HAZ0=
  kurabu:api.migrationPath:
    secure: AAABAG4rHJNhrJsqIyooYNJwzjpJk2isEJ/Yvwrtn9uBcAnkCWQyEupyRhdX5b7YZ+nCde2/2x3w9Q==
  kurabu:api.passwordEncryptionKey:
    secure: AAABAD73YbgNzBFuL5jAbjwWEkYC4H3kLE+X2p9QaSF9pNQZmcVGtRaSEBb/ILNWw7yYoxIJGfmOSC1BJAgurSDDxJP50CVFvTCBB5c1lwqf0jklUbobfN6rCRZXbkueeUCLh+ANiazEXK0rmubGGmhYOZBLrqkQwOjVmfTq/DHu6l8=
  kurabu:api.sendgridApiKey:
    secure: AAABAN7A1xDh310T8HazuZ5dE3SSL7s6K1lKZkjG8CWzzTGaONEIM5hfN4u6ZY2tZppAlgkq4BMazmh5TD/SNBcjTXu3+pAJEajjJEUSP+ecR7Kv1bcVWomM7g85qXW67b5xR60=
  kurabu:databaseMonitorEmail:
    secure: AAABAMo0Pnt38PzYWoHaTenUbm3GW7QBoZdf6C0evv1U65GzB5vhb5wdsag+LJ2Ip3ceqA==
  kurabu:databaseMonitorPassword:
    secure: AAABAJ4mCImvngdreU8aK/JvKjAERCPDmen/t6dLjmuLtdFizrnUG7lcHOqg/Y8u+TY8kA==
  kurabu:db.database:
    secure: AAABAPnErG8WRSaIyoqRI2u8Yq+IDBM+3TM7OnW0+kXL+9NZvhk=
  kurabu:db.password:
    secure: AAABACAkXzMU2kRyO24QU0GgMtvJ2exdryfrgzXWW7b1Xal7Wwce9Hx3mcwt6miaVeAHTzfg9JD+3AiWMV55
  kurabu:db.user:
    secure: AAABACrU74xWxZaaAqa3stxnECwbHBqOL3fUCbQyWv3nxc2ZGSU=
  kurabu:grafanaPassword:
    secure: AAABAJej7aQFX59GegcgrPTcR6QHXdOWOLQCL2gwNso/OJ7sYSzXISxFG7lmDlfG8YF1bQ==
  kurabu:kibanaMonitorPassword:
    secure: AAABAAahPbaySLMQRNwn+djMQux4ElGnfI2te4Iwsmw+3lzRjR3jLr+uJ42G1RvZwT6pFQ==
  kurabu:kibanaMonitorUser:
    secure: AAABALfqO8ga9SpYDcRoAPx6vdJaW8H3htY1FfZMl/4Oyun7qhT78DjpLCTj+QW8h1QH7w==
  kurabu:production: "true"
