apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- "../../core"

commonLabels:
  app: staging

namespace: staging       

resources:
- namespace.yaml
- ingress.yaml
- secret.yaml