apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: stage
  labels:
    app: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kurabu-api
  template:
    metadata:
      labels:
        app: kurabu-api
    spec:
      containers:
      - name: kurabu-api
        image: rafaeltab/kurabu.api:2.0.11
        env:
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: api.CLIENT_ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: api.CLIENT_SECRET
          - name: PASSWORD_ENCR
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: api.PASSWORD_ENCR
          - name: JWT_ENCRYPTION
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: api.JWT_ENCRYPTION
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: api.DATABASE_URL
          - name: SENDGRID_API_KEY
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: api.SENDGRID_API_KEY
          - name: MIGRATION_LOCATION
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: api.MIGRATION_LOCATION
          - name: EMAIL_DOMAIN
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: api.EMAIL_DOMAIN

        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "250Mi"
            cpu: "100m"
        ports:
        - containerPort: 15000
        

      
         