name: "Publish on push"

on:
  push:
    branches: [main]

jobs:
  check-build:
    name: Check build required
    runs-on: ubuntu-latest
    outputs:
      build_required_check: ${{ steps.check-full-turbo.outputs.build_required_check }}
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.after }}
          fetch-depth: 0
      
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check if build is required
        id: check-full-turbo
        env:
          REF: ${{ github.event.before }}
        run: |
          mkdir ./tmp
          mv ./.yarnrc.yml ./tmp/.yarnrc.yml

          yarn set version stable
          yarn plugin import workspace-tools
          yarn workspaces focus

          mv ./tmp/.yarnrc.yml ./.yarnrc.yml
          
          npm install -g turbo@1.5.5    

          set -x
          ls -la
          yarn dlx -q turbo@1.5.5 run check-build-required --filter=@kurabu/api...[$REF] --dry-run=json | tee ./check-build-required-tasks.txt
          cat ./check-build-required-tasks.txt | jq '.tasks | map(.cacheState | .local or .remote) | all' | tee ./check-build-required.txt
          set +x

          if grep -E -i -w -q "false" ./check-build-required.txt; then
            echo "::set-output name=build_required_check::required"
            echo "fullturbo"
          else
            echo "::set-output name=build_required_check::notrequired"
            echo "nofullturbo"
          fi

      - name: Display output
        run: echo "${{ toJson(steps.check-full-turbo.outputs) }}"

  build-docker:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: check-build
    if: ${{ needs.check-build.outputs.build_required_check == 'required' }}
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64/v8,arm64
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push docker image
        run: |
          mkdir ./tmp
          mv ./.yarnrc.yml ./tmp/.yarnrc.yml

          yarn set version stable
          yarn plugin import workspace-tools

          mv ./tmp/.yarnrc.yml ./.yarnrc.yml

          npm install -g turbo@1.5.5 ts-node    
          cd apps/api/scripts && npm install && cd ../../..
          
          yarn workspaces focus
        
          cat ./node_modules/.yarn-state.yml
          yarn run build:docker --filter=@kurabu/api

  publish-stage:
    name: Publish to staging
    runs-on: ubuntu-latest
    needs: build-docker
    environment: 
      name: Staging
      url: 'https://stage.kurabu.moe'
    steps:
      - name: "Start rollout"
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployments api-deployment -n=${{ secrets.NAMESPACE }}
  publish-prod:
    name: Publish to production
    runs-on: ubuntu-latest
    needs: build-docker
    environment: 
      name: Production
      url: 'https://prod.kurabu.moe'
    steps:
      - uses: imjasonh/setup-crane@v0.1
      - name: Retag image
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          crane auth login -u $username -p $password docker.io
          crane tag docker.io/rafaeltab/kurabu.api:latest production
      - name: "Start rollout"
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployments api-deployment -n=${{ secrets.NAMESPACE }}
