name: "Publish docker"

on:
  push:
    branches: [main]

jobs:
  # job for verifying content is not malicious?
  check-build:
    name: Check if a build is necessary
    runs-on: ubuntu-latest
    outputs:
      full_turbo_check: ${{ steps.check-full-turbo.outputs.full_turbo_check }}
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }}
      
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Remove yarnrc
        run: rm ./.yarnrc || rm ./.yarnrc.yml || yarn --version

      - name: Add turbo globally
        run: yarn global add turbo
      - name: Run the yarn run check-build-required
        run: yarn run check-build-required --cache-dir=/tmp/turbocache
      - run: ls -la /tmp/turbocache
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.after }}
      - name: Run the yarn run check-build-required
        run: |
          yarn run check-build-required --cache-dir=/tmp/turbocache > ./check-build-required.txt
          cat ./check-build-required.txt
      - name: Check if it is full turbo
        id: check-full-turbo
        run: |
          if grep -q "FULL TURBO" ./check-build-required.txt; then
            echo "::set-output name=full_turbo_check::fullturbo"
            echo "fullturbo"
          else
            echo "::set-output name=full_turbo_check::nofullturbo"
            echo "nofullturbo"
          fi
      - name: Display output
        run: echo "${{ toJson(steps.check-full-turbo.outputs) }}"
  bump-versions:
    name: Bump version numbers
    runs-on: ubuntu-latest
    needs: check-build
    if: ${{ needs.check-build.outputs.full_turbo_check == 'nofullturbo' }}
    steps:
      - name: Print output
        run: echo "${{ toJson(needs.check-build) }}"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.after }}
          fetch-depth: 0 
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Remove yarnrc
        run: rm ./.yarnrc || rm ./.yarnrc.yml || yarn --version
      - name: Add ts-node globally
        run: yarn global add ts-node
      - name: Install script dependencies
        run: cd scripts && npm install && cd ..

      - name: Get changed packages
        env:
          BEFORE_SHA: ${{ github.event.before }}
          AFTER_SHA: ${{ github.event.after }}
        run: |
          export CHANGED_JSONS="$(ts-node ./scripts/get-changes.ts)"
          echo $CHANGED_JSONS
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install script dependencies
        run: cd scripts && npm install && cd ..
      - name: Apply version changes
        run: ts-node ./scripts/bump-versions.ts

      - name: Configure git
        run: |
          git config --global user.email "${{ github.event.head_commit.committer.username }}@users.noreply.github.com"
          git config --global user.name "${{ github.event.head_commit.committer.name }}"
      - name: commit
        run: git commit -am "Bump version numbers"
      - name: push
        run: git push
  build-docker:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: bump-versions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Remove yarnrc
        run: rm ./.yarnrc || rm ./.yarnrc.yml || yarn --version
      - name: Add ts-node globally
        run: yarn global add turbo
      - name: Run docker build
        run: yarn run build:docker --scope=@kurabu/api
      - name: Upload image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: kurabu-api-image
          path: apps/api/docker/build/build.tar
     