name: "Publish docker"

on:
  push:
    branches: [main]

jobs:
  # job for verifying content is not malicious?
  check-build:
    name: Check if a build is necessary
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }}
      
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Remove yarnrc
        run: rm ./.yarnrc || rm ./.yarnrc.yml || yarn --version

      - name: Add turbo globally
        run: yarn global add turbo
      - name: Run the yarn run check-build-required
        run: yarn run check-build-required
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.after }}
      - name: Run the yarn run check-build-required
        run: yarn run check-build-required > ./check-build-required.txt
      - name: Check if it is full turbo
        run: |
          if grep -q "FULL TURBO" ./check-build-required.txt; then
            echo "::set-output name=full_turbo_check::true"
            echo "fullturbo"
          else
            echo "::set-output name=full_turbo_check::false"
            echo "nofullturbo"
          fi
  bump-versions:
    name: Bump version numbers
    runs-on: ubuntu-latest
    needs: check-build
    if: ${{ needs.check-build.outputs.full_turbo_check == false }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.after }}
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Remove yarnrc
        run: rm ./.yarnrc || rm ./.yarnrc.yml || yarn --version
      - name: Add ts-node globally
        run: yarn global add ts-node
      - name: Bump versions
        env:
          BEFORE_SHA: ${{ github.event.before }}
          AFTER_SHA: ${{ github.event.after }}
        run: ts-node ./scripts/bump-versions.ts
      - name: Add all
        run: git add -A
      - name: commit
        run: git commit -am "Bump version numbers"
      - name: push
        run: git push origin main
    